version: '3.4'
services:
    hcwm_front:
        build:
            context: hcwm_front
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_front"
        env_file:
            -   .env
        depends_on:
            - hcwm_backend
        networks:
            - default
        links:
            - hcwm_backend
        volumes:
            - ./hcwm_front:/app
        ports:
            - "${FRONT_APP_PORT_EXTERNAL}:80"

    #libretranslate:
    #  build:
    #    context: ../hcwm_translator
    #    dockerfile: docker/Dockerfile
    #  ports:
    #      - '5000:5000'
    hcwm_backend:
        build:
            context: ./hcwm
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_back"
        env_file:
            -   .env
        networks:
            - default
        links:
            - hcwm_mysql
            #- libretranslate
        volumes:
            - ./hcwm/:/var/www/html
            - ~/.ssh:/root/.ssh
        ports:
            - "${BACK_APP_PORT_EXTERNAL}:80"

    hcwm_adminer:
        image: "adminer"
        container_name: "hcwm_adminer"
        ports:
            - "9997:8080"
        links:
            - hcwm_mysql

    hcwm_mysql:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: "hcwm_mysql"
        ports:
            - "${DB_PORT_EXTERNAL}:3306"
        networks:
            - default
        volumes:
            - ./hcwm/docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
