version: '3.4'
services:
    frontend:
        build:
            context: hcwm_front
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_front"
        depends_on:
            - application
        networks:
            - default
        links:
            - application
        volumes:
            - ./hcwm_front:/app
            - ~/.ssh:/root/.ssh
        ports:
            - "8080:8080"
            - "80:80"

    #libretranslate:
    #  build:
    #    context: ../hcwm_translator
    #    dockerfile: docker/Dockerfile
    #  ports:
    #      - '5000:5000'
    application:
        build:
            context: ./hcwm
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_back"
        depends_on:
            - mysql
            #- libretranslate
        networks:
            - default
        links:
            - mysql
            #- libretranslate
        volumes:
            - ./hcwm/:/var/www/html
            - ~/.ssh:/root/.ssh
        ports:
            - "9999:80"

    adminer:
        image: "adminer"
        container_name: "hcwm_adminer"
        ports:
            - "9998:8080"
        links:
            - mysql

    mysql:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: "hcwm_mysql"
        ports:
            - "3306"
        networks:
            - default
        volumes:
            - ./hcwm/docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: odpady
            MYSQL_USER: 'mysql'
            MYSQL_PASSWORD: 'mysql'
            MYSQL_ROOT_HOST: '%'
