version: '3.4'
services:
    hcwm_front:
        build:
            context: hcwm_front
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_front"
        depends_on:
            - hcwm_backend
        networks:
            - default
        links:
            - hcwm_backend
        volumes:
            - ./hcwm_front:/app
            - ./hcwm_front/dist:/usr/share/nginx/html
            - ./hcwm_front/node_modules:/app/node_modules
            - ~/.ssh:/root/.ssh
        ports:
            - "8080:8080"
            - "80:80"

    #libretranslate:
    #  build:
    #    context: ../hcwm_translator
    #    dockerfile: docker/Dockerfile
    #  ports:
    #      - '5000:5000'
    hcwm_backend:
        build:
            context: ./hcwm
            dockerfile: docker/Dockerfile
        container_name: "hcwm_web_back"
        networks:
            - default
        links:
            - hcwm_mysql
            #- libretranslate
        volumes:
            - ./hcwm/:/var/www/html
            - ~/.ssh:/root/.ssh
        ports:
            - "3000:80"

    hcwm_adminer:
        image: "adminer"
        container_name: "hcwm_adminer"
        ports:
            - "9997:8080"
        links:
            - hcwm_mysql

    hcwm_mysql:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: "hcwm_mysql"
        ports:
            - "3306"
        networks:
            - default
        volumes:
            - ./hcwm/docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        environment:
            MYSQL_ROOT_PASSWORD: pOcNWRL7sTvk9AhB9ECo
            MYSQL_DATABASE: odpady
            MYSQL_USER: 'mysql'
            MYSQL_PASSWORD: 'mysql'
            MYSQL_ROOT_HOST: '%'
